version: "3"

services:
  client:
    #build: .
    #container_name: app-client
    image: app-client
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
