name: Format code

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Use Node.js version 17.5
      uses: actions/setup-node@v2
      with:
        node-version: "17.5"

    - name: Install dependencies
      run: npm install
    - name: Format code
      run: |
        npx prettier --write "src/**/*.js"
        npx eslint --fix --ext .js src/
    - name: Commit formatted code
      run: |
        eval $(ssh-agent)
        ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Auto-format code"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}