name: Format code

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Use Node.js version 17.5
      uses: actions/setup-node@v2
      with:
        node-version: "17.5"

    - name: Install dependencies
      run: npm install
    - name: Format code
      uses: actions/checkout@v2
      with:
        args: |
          npx prettier --write "src/**/*.js"
          npx eslint --fix --ext .js src/
    - name: Add and commit files
      run: |
        git checkout main
        git pull
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add .
          git commit -m "Fix code formatting with PHP-CS-Fixer"
          git push
        else
          echo "No changes to commit. Skipping git push."
        fi