name: Format code

on:
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Format code
      uses: actions/checkout@v2
      with:
        args: |
          npx prettier --write "src/**/*.js"
          npx eslint --fix --ext .js src/
    - name: Commit formatted code
      uses: elstudio/actions-git-push@v1.0.1
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true